2015-02-04 11:55:48,702:INFO:ServerLog:Local log started
2015-02-04 11:55:48,705:INFO:ServerLog:Log directory : .
2015-02-04 11:55:48,707:INFO:ServerLog:Port : 9020
2015-02-04 11:55:48,708:INFO:ServerLog:System path: ['/home/ict310/boinc-magphys_rep/boinc-magphys/server/src/logger', '/home/ict310/EC2TerminationNotices', '/home/ict310/EC2TerminationNotices/boinc-magphys/boinc-magphys/server/src', '/usr/local/lib/python27.zip', '/usr/local/lib/python2.7', '/usr/local/lib/python2.7/plat-linux3', '/usr/local/lib/python2.7/lib-tk', '/usr/local/lib/python2.7/lib-old', '/usr/local/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/site-packages', '/usr/local/lib/python2.7/site-packages/PIL', '/home/ict310/EC2TerminationNotices/boinc-magphys/boinc-magphys/server/src', '/home/ict310/EC2TerminationNotices/boinc-magphys/boinc/py']
2015-02-04 11:55:48,709:INFO:ServerLog:Log directory already exists at ./
2015-02-04 11:55:48,709:INFO:ServerLog:Attempting to set up sockets...
2015-02-04 11:55:48,711:INFO:ServerLog:Listening on  : 9020
2015-02-04 11:55:51,285:INFO:ServerLog:Caught sigint
2015-02-04 11:55:53,065:INFO:ServerLog:Local log started
2015-02-04 11:55:53,066:INFO:ServerLog:Log directory : .
2015-02-04 11:55:53,067:INFO:ServerLog:Port : 9020
2015-02-04 11:55:53,067:INFO:ServerLog:System path: ['/home/ict310/boinc-magphys_rep/boinc-magphys/server/src/logger', '/home/ict310/EC2TerminationNotices', '/home/ict310/EC2TerminationNotices/boinc-magphys/boinc-magphys/server/src', '/usr/local/lib/python27.zip', '/usr/local/lib/python2.7', '/usr/local/lib/python2.7/plat-linux3', '/usr/local/lib/python2.7/lib-tk', '/usr/local/lib/python2.7/lib-old', '/usr/local/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/site-packages', '/usr/local/lib/python2.7/site-packages/PIL', '/home/ict310/EC2TerminationNotices/boinc-magphys/boinc-magphys/server/src', '/home/ict310/EC2TerminationNotices/boinc-magphys/boinc/py']
2015-02-04 11:55:53,072:INFO:ServerLog:Log directory already exists at ./
2015-02-04 11:55:53,072:INFO:ServerLog:Attempting to set up sockets...
2015-02-04 11:55:53,074:INFO:ServerLog:Listening on  : 9020
2015-02-04 11:55:55,305:INFO:ServerLog:Caught sigint
2015-02-04 11:55:56,264:INFO:ServerLog:Local log started
2015-02-04 11:55:56,266:INFO:ServerLog:Log directory : .
2015-02-04 11:55:56,267:INFO:ServerLog:Port : 9020
2015-02-04 11:55:56,267:INFO:ServerLog:System path: ['/home/ict310/boinc-magphys_rep/boinc-magphys/server/src/logger', '/home/ict310/EC2TerminationNotices', '/home/ict310/EC2TerminationNotices/boinc-magphys/boinc-magphys/server/src', '/usr/local/lib/python27.zip', '/usr/local/lib/python2.7', '/usr/local/lib/python2.7/plat-linux3', '/usr/local/lib/python2.7/lib-tk', '/usr/local/lib/python2.7/lib-old', '/usr/local/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/site-packages', '/usr/local/lib/python2.7/site-packages/PIL', '/home/ict310/EC2TerminationNotices/boinc-magphys/boinc-magphys/server/src', '/home/ict310/EC2TerminationNotices/boinc-magphys/boinc/py']
2015-02-04 11:55:56,268:INFO:ServerLog:Log directory already exists at ./
2015-02-04 11:55:56,268:INFO:ServerLog:Attempting to set up sockets...
2015-02-04 11:55:56,270:INFO:ServerLog:Listening on  : 9020
2015-02-04 11:55:59,927:INFO:ServerLog:Caught sigint
2015-02-04 11:56:22,225:INFO:ServerLog:Local log started
2015-02-04 11:56:22,227:INFO:ServerLog:Log directory : .
2015-02-04 11:56:22,228:INFO:ServerLog:Port : 9020
2015-02-04 11:56:22,229:INFO:ServerLog:System path: ['/home/ict310/boinc-magphys_rep/boinc-magphys/server/src/logger', '/usr/local/lib/python27.zip', '/usr/local/lib/python2.7', '/usr/local/lib/python2.7/plat-linux3', '/usr/local/lib/python2.7/lib-tk', '/usr/local/lib/python2.7/lib-old', '/usr/local/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/site-packages', '/usr/local/lib/python2.7/site-packages/PIL', '/home/ict310/boinc-magphys_rep/boinc-magphys/server/src', '/home/ict310/boinc-magphys_rep/boinc/py']
2015-02-04 11:56:22,229:INFO:ServerLog:Log directory already exists at ./
2015-02-04 11:56:22,230:INFO:ServerLog:Attempting to set up sockets...
2015-02-04 11:56:22,231:INFO:ServerLog:Listening on  : 9020
2015-02-04 11:56:23,653:INFO:ServerLog:Caught sigint
2015-02-04 11:56:25,544:INFO:ServerLog:Local log started
2015-02-04 11:56:25,545:INFO:ServerLog:Log directory : .
2015-02-04 11:56:25,545:INFO:ServerLog:Port : 9020
2015-02-04 11:56:25,546:INFO:ServerLog:System path: ['/home/ict310/boinc-magphys_rep/boinc-magphys/server/src/logger', '/usr/local/lib/python27.zip', '/usr/local/lib/python2.7', '/usr/local/lib/python2.7/plat-linux3', '/usr/local/lib/python2.7/lib-tk', '/usr/local/lib/python2.7/lib-old', '/usr/local/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/site-packages', '/usr/local/lib/python2.7/site-packages/PIL', '/home/ict310/boinc-magphys_rep/boinc-magphys/server/src', '/home/ict310/boinc-magphys_rep/boinc/py']
2015-02-04 11:56:25,546:INFO:ServerLog:Log directory already exists at ./
2015-02-04 11:56:25,547:INFO:ServerLog:Attempting to set up sockets...
2015-02-04 11:56:25,547:INFO:ServerLog:Listening on  : 9020
2015-02-04 11:56:30,045:INFO:ServerLog:Local log started
2015-02-04 11:56:30,046:INFO:ServerLog:Log directory : .
2015-02-04 11:56:30,046:INFO:ServerLog:Port : 9020
2015-02-04 11:56:30,046:INFO:ServerLog:System path: ['/home/ict310/boinc-magphys_rep/boinc-magphys/server/src/logger', '/usr/local/lib/python27.zip', '/usr/local/lib/python2.7', '/usr/local/lib/python2.7/plat-linux3', '/usr/local/lib/python2.7/lib-tk', '/usr/local/lib/python2.7/lib-old', '/usr/local/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/site-packages', '/usr/local/lib/python2.7/site-packages/PIL', '/home/ict310/boinc-magphys_rep/boinc-magphys/server/src', '/home/ict310/boinc-magphys_rep/boinc/py']
2015-02-04 11:56:30,047:INFO:ServerLog:Log directory already exists at ./
2015-02-04 11:56:30,047:INFO:ServerLog:Attempting to set up sockets...
2015-02-04 11:56:30,048:ERROR:ServerLog:Error setting up sockets. Is there another process listening on port 9020 ?
Traceback (most recent call last):
  File "./server_socket_logger_process.py", line 135, in main
    server_socket.bind((local_host, local_port))
  File "/usr/local/lib/python2.7/socket.py", line 222, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use
2015-02-04 11:56:42,346:INFO:ServerLog:Local log started
2015-02-04 11:56:42,347:INFO:ServerLog:Log directory : .
2015-02-04 11:56:42,347:INFO:ServerLog:Port : 9020
2015-02-04 11:56:42,347:INFO:ServerLog:System path: ['/home/ict310/boinc-magphys_rep/boinc-magphys/server/src/logger', '/usr/local/lib/python27.zip', '/usr/local/lib/python2.7', '/usr/local/lib/python2.7/plat-linux3', '/usr/local/lib/python2.7/lib-tk', '/usr/local/lib/python2.7/lib-old', '/usr/local/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/site-packages', '/usr/local/lib/python2.7/site-packages/PIL', '/home/ict310/boinc-magphys_rep/boinc-magphys/server/src', '/home/ict310/boinc-magphys_rep/boinc/py']
2015-02-04 11:56:42,348:INFO:ServerLog:Log directory already exists at ./
2015-02-04 11:56:42,348:INFO:ServerLog:Attempting to set up sockets...
2015-02-04 11:56:42,349:ERROR:ServerLog:Error setting up sockets. Is there another process listening on port 9020 ?
Traceback (most recent call last):
  File "./server_socket_logger_process.py", line 135, in main
    server_socket.bind((local_host, local_port))
  File "/usr/local/lib/python2.7/socket.py", line 222, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use
2015-02-04 11:57:55,451:INFO:ServerLog:Local log started
2015-02-04 11:57:55,452:INFO:ServerLog:Log directory : .
2015-02-04 11:57:55,453:INFO:ServerLog:Port : 9020
2015-02-04 11:57:55,453:INFO:ServerLog:System path: ['/home/ict310/boinc-magphys_rep/boinc-magphys/server/src/logger', '/usr/local/lib/python27.zip', '/usr/local/lib/python2.7', '/usr/local/lib/python2.7/plat-linux3', '/usr/local/lib/python2.7/lib-tk', '/usr/local/lib/python2.7/lib-old', '/usr/local/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/site-packages', '/usr/local/lib/python2.7/site-packages/PIL', '/home/ict310/boinc-magphys_rep/boinc-magphys/server/src', '/home/ict310/boinc-magphys_rep/boinc/py']
2015-02-04 11:57:55,454:INFO:ServerLog:Log directory already exists at ./
2015-02-04 11:57:55,454:INFO:ServerLog:Attempting to set up sockets...
2015-02-04 11:57:55,456:ERROR:ServerLog:Error setting up sockets. Is there another process listening on port 9020 ?
Traceback (most recent call last):
  File "./server_socket_logger_process.py", line 135, in main
    server_socket.bind((local_host, local_port))
  File "/usr/local/lib/python2.7/socket.py", line 222, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use
2015-02-04 12:04:17,641:INFO:ServerLog:Local log started
2015-02-04 12:04:17,642:INFO:ServerLog:Log directory : .
2015-02-04 12:04:17,642:INFO:ServerLog:Port : 9020
2015-02-04 12:04:17,643:INFO:ServerLog:System path: ['/home/ict310/boinc-magphys_rep/boinc-magphys/server/src/logger', '/usr/local/lib/python27.zip', '/usr/local/lib/python2.7', '/usr/local/lib/python2.7/plat-linux3', '/usr/local/lib/python2.7/lib-tk', '/usr/local/lib/python2.7/lib-old', '/usr/local/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/site-packages', '/usr/local/lib/python2.7/site-packages/PIL', '/home/ict310/boinc-magphys_rep/boinc-magphys/server/src', '/home/ict310/boinc-magphys_rep/boinc/py']
2015-02-04 12:04:17,643:INFO:ServerLog:Log directory already exists at ./
2015-02-04 12:04:17,644:INFO:ServerLog:Attempting to set up sockets...
2015-02-04 12:04:17,645:INFO:ServerLog:Listening on  : 9020
